sudo: false
language: cpp

compiler:
 - clang
 - gcc

env:
  matrix:
    - CONF=debug   ARCH=x86_64
    - CONF=release ARCH=x86_64
  global:
    - ARCH_FLAGS_x86_64=''
    - secure: "todo"

addons:
  apt:
   sources:
   - ubuntu-toolchain-r-test # gcc5.2
   - george-edison55-precise-backports # cmake doxygen
   packages:
   - gcc-5
   - g++-5
   - cmake
   - cmake-data
   - doxygen
   - qtbase5-dev
   - qtdeclarative5-dev

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

script:
 - mkdir -v build
 - eval "ARCH_FLAGS=\${ARCH_FLAGS_${ARCH}}" \
   && cd build
   && cmake \
   -DCMAKE_VERBOSE_MAKEFILE=ON \
   -DCMAKE_BUILD_TYPE=$CONF \
   -DCMAKE_CXX_FLAGS="$ARCH_FLAGS" ..
 - make
