# https://docs.travis-ci.com/user/languages/minimal-and-generic/
language: minimal
dist: bionic

# no install step to perform
install: true

# When a script command fails, travis run the next one so we must use
# `travis_terminate 1`
script:
  - >
    echo 'travis_fold:start:build_env'
    && make env
    && echo 'travis_fold:end:build_env'
    || travis_terminate 1

  - >
    echo 'travis_fold:start:build_devel'
    && make devel
    && echo 'travis_fold:end:build_devel'
    || travis_terminate 1

  - >
    echo 'travis_fold:start:test_devel'
    && make test_devel
    && echo 'travis_fold:end:test_devel'
    || travis_terminate 1
